# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-22 14:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_auto_20161118_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank='True', null='True', upload_to='images'),
        ),
    ]
