# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-16 16:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_blog_store'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
